import json, os

entries = [
  {"e":"🤣","slug":"rolling-on-floor-laughing","name":"Rolling on the Floor Laughing","aliases":"ROFL, rolling on floor laughing, laughing hard, hilarious, dead","meaning":"The <strong>Rolling on the Floor Laughing</strong> (🤣) emoji shows a face tilted sideways, laughing uncontrollably with tears. It is one step beyond 😂 — you are not just crying-laughing, you are <strong>literally rolling on the ground</strong>. The tilted angle is what makes it distinct: it conveys that the laughter is so intense you have lost physical control.<br><br>Use 🤣 when 😂 does not feel strong enough. It is the emoji for when something is so funny you cannot type properly. In group chats, it is the standard reaction to the funniest joke of the day. Some Gen Z users prefer 💀 (skull) for extreme laughter — 🤣 can feel slightly millennial in certain contexts.","usage":["This stand-up special had me the entire time","When your friend retells the most embarrassing story","The autocorrect fail screenshot sent me"],"related":["😂","💀","😹","😭","😆"],"cat":"smileys"},
  {"e":"🙏","slug":"folded-hands","name":"Folded Hands","aliases":"folded hands, pray, please, thank you, high five, namaste","meaning":"The <strong>Folded Hands</strong> (🙏) emoji is one of the most debated in emoji history. Two hands pressed together. In Japan, it means \"please\" or \"thank you\" (a common gesture in daily life). In Western countries, it is widely used as \"prayer\" or \"hope.\" In some communities, it is interpreted as a \"high five.\"<br><br>Use it to express gratitude (\"Thank you so much\"), hope (\"Please let this work out\"), or a respectful greeting (\"Namaste\"). Context usually makes the meaning clear. It is also commonly used in sports contexts as a high five celebration.","usage":["Praying for good news","Thank you for all the support","Please let me pass this exam"],"related":["🤲","🯎","✨","🛐","🤝"],"cat":"gestures"},
  {"e":"👀","slug":"eyes","name":"Eyes","aliases":"eyes, looking, watching, side eye, staring","meaning":"The <strong>Eyes</strong> (👀) emoji shows a pair of wide-open eyes looking to the left. It is universally used to mean <strong>\"I see this,\" \"look at this,\" or \"this is interesting.\"</strong> It is the digital equivalent of leaning in and paying attention.<br><br>It is the go-to reaction when someone drops surprising information in a group chat. It is also the standard emoji for gossip, drama, or anything eyebrow-raising. On social media, brands and personalities use it to tease upcoming announcements. The eyes work because they are ambiguous — they could mean curiosity, attraction, suspicion, or just that something caught your attention.","usage":["Did you see the drama in the group chat","New job announcement coming next week","That is an interesting choice"],"related":["😳","🤔","🧐","😏","🫣"],"cat":"smileys"},
  {"e":"💯","slug":"hundred-points","name":"Hundred Points","aliases":"100, hundred points, perfect, keep it 100, a plus","meaning":"The <strong>Hundred Points</strong> (💯) emoji shows the number 100 underlined, as if written on a perfect test. It means <strong>\"completely agree,\" \"absolutely correct,\" or \"perfect.\"</strong> It is the strongest endorsement you can give in emoji form.<br><br>Originally from the phrase \"keep it 100\" (keep it real, be authentic), 💯 has expanded to mean any form of full agreement or validation. In Black Twitter culture, it is a classic affirmation emoji. It is also used as a rating for anything exceptional. Unlike 👍 (which means \"okay\") or 🔥 (which means \"impressive\"), 💯 means \"I could not agree more.\"","usage":["This take is correct","Keep it real always","Best pizza in the city no competition"],"related":["🔥","👍","✅","💪","🙌"],"cat":"symbols"},
  {"e":"❤️","slug":"red-heart","name":"Red Heart","aliases":"red heart, love, like, favorite, heart emoji, classic heart","meaning":"The <strong>Red Heart</strong> (❤️) is the most used emoji symbol in the world. Representing the classic red heart shape, it conveys <strong>love, affection, care, and deep emotional connection</strong>. It works in romantic, platonic, familial, and even casual contexts.<br><br>Unlike the newer heart color variants, ❤️ remains the gold standard. It is the most serious heart — when someone switches from colored hearts to ❤️, it often signals deepening feelings. On Instagram and TikTok, it is the universal \"like\" reaction. The red heart has been an emoji since the earliest days of Unicode, making it one of the most tested and trusted symbols in digital communication.","usage":["Thinking of you","This song has my whole heart","Goodnight love you"],"related":["💕","💗","💖","😍","🥰"],"cat":"symbols"},
  {"e":"🤡","slug":"clown-face","name":"Clown Face","aliases":"clown, ridiculous, foolish, embarrassing, clowning","meaning":"The <strong>Clown Face</strong> (🤡) emoji is one of the most brutal insults in the emoji keyboard. It is used to call someone <strong>ridiculous, foolish, or a joke</strong>. If someone replies to your take with 🤡, they are not laughing with you — they are laughing at you.<br><br>On Twitter and TikTok, 🤡 is the standard reaction to bad takes, hypocrisy, and embarrassing behavior. It is also used self-deprecatingly. The clown emoji gained massive popularity during political discourse as shorthand for calling out dishonesty. In meme culture, the \"clown makeup\" progression is often summarized with a single 🤡. Use it carefully — it can be playful among friends but genuinely insulting in public conversations.","usage":["This aged poorly","Me after that terrible life decision","The whole situation is a circus"],"related":["🙃","😬","🟿","💀","🎪"],"cat":"smileys"},
  {"e":"🥵","slug":"hot-face","name":"Hot Face","aliases":"hot face, overheated, sweating, attractive, spicy","meaning":"The <strong>Hot Face</strong> (🥵) emoji shows a red-faced, sweating emoji with its tongue hanging out — the universal sign of being <strong>extremely hot or overheated</strong>. But its meaning has expanded to also mean someone or something is <strong>attractive or \"hot.\"</strong><br><br>Literally: \"It is 100 degrees and no AC.\" Figuratively: \"That photoshoot\" (meaning: they look incredibly attractive). In fitness communities, it is the post-workout emoji. It can also mean food is spicy. The dual meaning makes it a playful, versatile addition to any message.","usage":["Summer in Texas be like","That new profile picture","This curry is no joke"],"related":["🥶","😰","😅","🔥","🫠"],"cat":"smileys"},
  {"e":"🥶","slug":"cold-face","name":"Cold Face","aliases":"cold face, freezing, blue, icy, freezing cold, left on read","meaning":"The <strong>Cold Face</strong> (🥶) emoji shows a blue, shivering face with icicles hanging from its jaw. It represents <strong>extreme cold, being frozen, or (metaphorically) being ignored or given the cold shoulder.</strong><br><br>Literally: \"Waiting for the bus in January.\" Figuratively: \"He left me on read\" — the cold shoulder interpretation. In sports contexts, 🥶 also means someone is <strong>ice cold</strong> in a positive way — calm under pressure, clutch: \"That game-winning shot was.\" The icicles are the key visual that distinguish this from simply being unhappy.","usage":["Canadian winter mornings","She did not even say hi","That penalty kick under pressure was ice cold"],"related":["🥵","😰","🧊","❄️","😬"],"cat":"smileys"},
  {"e":"🫣","slug":"face-with-peeking-eye","name":"Face with Peeking Eye","aliases":"peeking, hiding, watching through fingers, cannot look, scared to watch","meaning":"The <strong>Face with Peeking Eye</strong> (🫣) shows hands covering a face — except one eye is peeking through between the fingers. It captures the universal gesture of <strong>watching something through your fingers because you are scared, embarrassed, or cannot look away.</strong><br><br>Use it when watching a horror movie, experiencing secondhand embarrassment, or when you are curious about something you probably should not be looking at. Introduced in 2022, it quickly became a favorite because it captures a very specific and relatable human gesture.","usage":["Watching the scary movie like","Me reading the group chat drama","When the presentation is going really badly"],"related":["🙈","😳","😬","🤭","🫢"],"cat":"smileys"},
  {"e":"🫢","slug":"face-with-hand-over-mouth","name":"Face with Open Eyes and Hand Over Mouth","aliases":"gasp, shocked, surprised, hand over mouth, oops, did I just say that","meaning":"The <strong>Face with Hand Over Mouth</strong> (🫢) shows a face with wide eyes and a hand covering the mouth — the classic <strong>\"I cannot believe I just said that\"</strong> expression. It conveys shock, surprise, or the moment you realize you have made a mistake.<br><br>Unlike 😱 (scream), which is about fear, 🫢 is about <strong>social surprise</strong> — saying something you should not have, hearing unexpected gossip, or witnessing an awkward moment. The combination of wide eyes (surprise) plus covered mouth (the urge to suppress a reaction) makes it feel more nuanced and realistic than simpler shock emojis.","usage":["When you accidentally hit reply all","Did he really just say that","The plot twist in episode 6 had me"],"related":["😱","😮","🤭","🫣","😳"],"cat":"smileys"},
]

# Append to MORE_DATA in generator
with open('/Users/fanny/DevProjects/Tools/emoji101/generate_meanings.py', 'r') as f:
    content = f.read()

# Find the closing bracket of MORE_DATA
more_start = content.find('MORE_DATA = [')
bracket = content.find('\n]', more_start)
if bracket == -1:
    bracket = content.find(']', more_start)

new_code = ',\n'.join([json.dumps(e, ensure_ascii=False) for e in entries])
content = content[:bracket] + ',\n' + new_code + '\n' + content[bracket:]

with open('/Users/fanny/DevProjects/Tools/emoji101/generate_meanings.py', 'w') as f:
    f.write(content)

print(f'Added {len(entries)} entries to MORE_DATA')
