import json

entries = [
  {"e":"🥳","slug":"partying-face","name":"Partying Face","aliases":"party, celebration, birthday, hat, horn, lets go","meaning":"The <strong>Partying Face</strong> (🥳) emoji shows a smiling face with a party hat and a party horn. It is the universal emoji for <strong>celebration, birthdays, and good times</strong>. Whether it is an actual birthday (\"Happy birthday\"), a milestone achieved (\"Got the job\"), or just a Friday night (\"Weekend\"), 🥳 brings the party.<br><br>Use it for congratulations, New Year celebrations, or any moment that deserves festive energy. It can also be used ironically when something is underwhelming: \"Wow an extra 5 minutes of break time.\" The party hat makes it unmistakably festive — there is no ambiguity about the mood.","usage":["Happy birthday","Weekend starts now","Got the promotion"],"related":["🎉","🎂","🎊","🥂","🎈"],"cat":"smileys"},
  {"e":"🎉","slug":"party-popper","name":"Party Popper","aliases":"party, celebration, confetti, congratulations, tada","meaning":"The <strong>Party Popper</strong> (🎉) emoji shows a party popper bursting with confetti and streamers. It represents <strong>celebration, congratulations, and exciting announcements</strong>. It is the emoji equivalent of popping a champagne bottle.<br><br>Use it for major life announcements (\"We are engaged\"), professional wins (\"Launched the product\"), or general good news (\"Passed my exam\"). The confetti pattern makes it instantly recognizable as a celebration marker. It pairs perfectly with 🥳 (partying face) and 🎊 (confetti ball) for maximum festive impact.","usage":["We did it","New job starts Monday","Happy New Year"],"related":["🥳","🎊","🥂","🎂","✨"],"cat":"smileys"},
  {"e":"💔","slug":"broken-heart","name":"Broken Heart","aliases":"broken heart, heartbreak, sad, lost love, emotional pain","meaning":"The <strong>Broken Heart</strong> (💔) emoji shows a red heart split in two with a crack down the middle. It represents <strong>heartbreak, emotional pain, loss, and grief</strong>. Unlike ❤️ which is about love and connection, 💔 is explicitly about love that has been damaged or lost.<br><br>Use it for romantic heartbreak (\"Just went through a breakup\"), general sadness (\"My favorite show ended\"), or empathy (\"That story broke my heart\"). It can also express disappointment: \"They canceled my flight last minute.\" The visual of the cracked heart makes the pain feel tangible — the love is not just gone, it is broken.","usage":["Going through a rough breakup","This news is devastating","Saying goodbye to my childhood home"],"related":["❤️","😢","😭","💕","🥺"],"cat":"symbols"},
  {"e":"🤓","slug":"nerd-face","name":"Nerd Face","aliases":"nerd, geek, smart, studious, glasses, dork","meaning":"The <strong>Nerd Face</strong> (🤓) emoji shows a smiling face with thick black glasses and buck teeth. It represents <strong>intelligence, enthusiasm for niche interests, or being socially awkward in an endearing way</strong>. Once an insult, \"nerd\" has been reclaimed as a badge of honor in the internet age.<br><br>Use it to show genuine enthusiasm for something academic or technical (\"Just spent 3 hours organizing my spreadsheet\"), or to be self-deprecating about being overly excited about something (\"Me explaining why this movie is actually a masterpiece\"). It can also literally mean someone who is studying or reading. In recent years, 🤓 has become less about mockery and more about proudly owning your interests.","usage":["Actually according to my calculations","Me at trivia night","Just finished a 500 page book in one sitting"],"related":["🧐","🤔","📚","💻","🧠"],"cat":"smileys"},
  {"e":"🤧","slug":"sneezing-face","name":"Sneezing Face","aliases":"sneeze, sick, allergies, cold, tissue, bless you","meaning":"The <strong>Sneezing Face</strong> (🤧) emoji shows a face with closed eyes and a tissue held to its nose — mid-sneeze. It represents <strong>sickness, allergies, or the common cold</strong>. But it has also been adopted as the emoji for <strong>ugly crying</strong> — the kind of crying that leaves you reaching for tissues.<br><br>Literally: \"This allergy season is killing me.\" Figuratively: \"That movie ending.\" The dual meaning (sickness vs. emotional crying) is similar to 😭 which also spans literal tears and emotional overwhelm. In anime and K-drama fan communities, 🤧 is the standard reaction to emotionally devastating scenes — you are not just crying, you need tissues.","usage":["Pollen count is off the charts today","When the K-drama episode ends on a cliffhanger","Sick in bed all weekend"],"related":["😭","😢","😷","🤒","🥲"],"cat":"smileys"},
  {"e":"😤","slug":"face-with-steam-from-nose","name":"Face with Steam From Nose","aliases":"frustrated, angry, steam, triumph, determination, fed up","meaning":"The <strong>Face with Steam From Nose</strong> (😤) shows a scowling face with steam blowing from its nostrils — like an angry cartoon bull. It represents <strong>frustration, determination, or feeling fed up</strong>. It is the \"I am so done\" emoji.<br><br>The steam from the nose is what distinguishes this from other anger emojis. It implies the anger is building up, about to boil over — not explosive rage (😡) but simmering frustration. Use it for minor but persistent annoyances (\"The printer jammed AGAIN\") or for showing competitive determination (\"I am going to beat this level if it kills me\"). In sports contexts, it can mean \"I am locked in\" or \"I am coming for that title.\"","usage":["Fourth time restarting the computer today","When your team is losing and there are 2 minutes left","I will finish this project tonight no matter what"],"related":["😡","😠","💢","🤬","😮‍💨"],"cat":"smileys"},
  {"e":"🥹","slug":"face-holding-back-tears","name":"Face Holding Back Tears","aliases":"holding back tears, touched, moved, emotional, about to cry, grateful","meaning":"The <strong>Face Holding Back Tears</strong> (🥹) shows a face with wide, glossy eyes and a slight wobble in the expression — someone who is <strong>trying not to cry</strong>. It is the emoji for being profoundly moved, deeply grateful, or emotionally overwhelmed in a positive way.<br><br>This is NOT a sad emoji. It is about being touched by kindness: \"You remembered my favorite coffee order.\" Or being overcome by a beautiful moment: \"My baby said mama for the first time.\" Or gratitude: \"This community came through for me.\" The held-back tears imply the emotion is so strong it cannot be contained, but you are trying to keep it together. Introduced in 2022, it quickly became a favorite for wholesome, heartfelt moments.","usage":["When your friend throws you a surprise party","This comment made my whole week","My parents reaction to the good news"],"related":["🥲","😭","😢","🥺","😊"],"cat":"smileys"},
  {"e":"😳","slug":"flushed-face","name":"Flushed Face","aliases":"flushed, embarrassed, blushing, shocked, wide eyes, caught off guard","meaning":"The <strong>Flushed Face</strong> (😳) shows a face with wide eyes, raised eyebrows, and red cheeks — the universal <strong>\"I am embarrassed\" or \"I was not expecting that\"</strong> expression. It conveys surprise, embarrassment, or being caught off guard by something unexpected.<br><br>Use it when someone says something unexpectedly flirty (\"Oh, um, thank you\"), when you realize you have made a mistake (\"Just realized I have been pronouncing that wrong\"), or when you see something shocking (\"Did not expect that plot twist\"). The flushed cheeks are key — they show the physical reaction of blushing, which makes the embarrassment feel visceral and real. In flirty contexts, 😳 signals that you are pleasantly flustered.","usage":["When your crush compliments you","Wait what did you just say","Me realizing the meeting was yesterday not today"],"related":["😊","😏","🫣","😅","😬"],"cat":"smileys"},
  {"e":"😬","slug":"grimacing-face","name":"Grimacing Face","aliases":"grimacing, awkward, cringe, yikes, nervous smile, teeth","meaning":"The <strong>Grimacing Face</strong> (😬) shows a face with clenched teeth in an awkward grimace. It is the <strong>\"yikes\"</strong> emoji — the face you make when something is awkward, uncomfortable, or you are in a tough spot but trying to smile through it.<br><br>Use it for secondhand embarrassment (\"That was hard to watch\"), stressful situations (\"The boss just asked who did this\"), or acknowledging an uncomfortable truth (\"When someone asks about your ex\"). The clenched teeth are the defining feature — you are technically \"smiling\" but it is clearly forced. It is the emoji equivalent of sucking air through your teeth and going \"eeeesh.\"","usage":["When the professor says check your own work and swap with a partner","That joke did not land at all","Me reading old Facebook posts from 2012"],"related":["😅","🫠","😰","🙃","😮‍💨"],"cat":"smileys"},
  {"e":"💖","slug":"sparkling-heart","name":"Sparkling Heart","aliases":"sparkling heart, excited love, grateful, touched, new love","meaning":"The <strong>Sparkling Heart</strong> (💖) shows a pink heart surrounded by sparkles. It is more excited and grateful than ❤️ — adding sparkle suggests the love is <strong>fresh, exciting, or deeply appreciated</strong>. It is the heart you use when someone does something unexpectedly thoughtful.<br><br>Use it for showing excited gratitude (\"You got me concert tickets\"), expressing that something made your heart sparkle (\"This baby photo\"), or marking a special romantic moment (\"First anniversary\"). It is less serious than ❤️ and more energetic than 💕. The sparkles make it feel like the love is radiating outward — it is not just a feeling, it is visible. In fandom communities, 💖 is the standard heart for expressing love for a favorite character or ship.","usage":["You are the sweetest person ever","This made my whole day sparkle","Look at this adorable puppy video"],"related":["❤️","💕","💗","✨","🥰"],"cat":"symbols"},
  {"e":"🎯","slug":"direct-hit","name":"Direct Hit","aliases":"bullseye, spot on, exactly right, target, nailed it, on point","meaning":"The <strong>Direct Hit</strong> (🎯) emoji shows a dart hitting the exact center of a target. It means <strong>\"exactly right,\" \"spot on,\" or \"you nailed it.\"</strong> It is the emoji for when someone perfectly articulates something you have been thinking.<br><br>Use it when agreeing strongly with an opinion (\"This thread is right on the money\"), when someone accurately describes you (\"How did you know\"), or for precision in general (\"The forecast predicted rain to the minute\"). In work contexts, it can mean \"hitting a target\" or achieving a goal: \"Q3 numbers right on target.\" It is a stronger endorsement than 👍 (I agree) — 🎯 means \"you could not have said it better.\"","usage":["This take is spot on","When the description is too accurate","Right on target for our monthly goal"],"related":["💯","👍","✅","🔥","👌"],"cat":"activities"},
  {"e":"🚩","slug":"triangular-flag","name":"Triangular Flag","aliases":"red flag, warning, alert, danger, red flag emoji","meaning":"The <strong>Triangular Flag</strong> (🚩) emoji shows a red flag on a pole. It has become the internet standard for signaling <strong>warning signs, dealbreakers, or toxic behavior</strong> — especially in dating and relationships. When someone describes concerning behavior and you reply with 🚩, you are saying \"that is a red flag.\"<br><br>The \"red flag\" meme exploded on social media around 2022 when people started listing red flags in partners, jobs, friendships, and brands. \"He was rude to the waiter — 🚩.\" \"The job posting says we are a family — 🚩.\" Beyond relationships, any warning sign can be flagged. In sports, the literal meaning (a penalty flag) is also used. In hiking and outdoor contexts, it can mean trail markers. But the dominant meaning on social media is the figurative warning signal.","usage":["He still talks to his ex every day","The apartment listing says cozy which means tiny","Job interview asked if I am willing to work weekends for free"],"related":["⛳","⚠️","❗","❌","💀"],"cat":"symbols"},
  {"e":"🌈","slug":"rainbow","name":"Rainbow","aliases":"rainbow, pride, LGBTQ, hope, colorful, after the storm, weather","meaning":"The <strong>Rainbow</strong> (🌈) emoji shows a colorful rainbow arc. It carries multiple layers of meaning: <strong>LGBTQ+ pride, hope after hardship, weather, and general positivity</strong>. It is one of the most culturally significant emojis, serving as both a literal weather symbol and a powerful identity marker.<br><br>As a pride symbol, 🌈 represents the LGBTQ+ community and is widely used during Pride Month (June) and year-round as a show of support. As a metaphor, it represents hope and optimism — \"after every storm comes a rainbow.\" It can also mean something colorful and cheerful: \"My new nail set.\" The rainbow has been a symbol of diversity and inclusion since the 1970s, and the emoji carries that legacy into digital communication.","usage":["Happy Pride Month","Things will get better","The most beautiful sunset with a double rainbow"],"related":["🏳️‍🌈","☀️","🌦️","✨","💖"],"cat":"animals"},
  {"e":"🎂","slug":"birthday-cake","name":"Birthday Cake","aliases":"birthday cake, happy birthday, celebration, cake, birthday","meaning":"The <strong>Birthday Cake</strong> (🎂) emoji shows a decorated cake with lit candles. It is the universal symbol for <strong>birthdays and celebrations</strong>. Sending 🎂 is the quickest way to say \"happy birthday\" without words.<br><br>Use it for literal birthdays (\"Happy birthday\"), anniversaries, or milestones that deserve cake. It can also mean the actual food: \"Baking a cake this weekend.\" Paired with 🥳 (partying face) and 🎉 (party popper), it forms the standard birthday message trio. In professional contexts, it can mark a company anniversary or product launch: \"One year since we launched.\" The candles imply something worth celebrating — it is not just any cake, it is a cake for a special occasion.","usage":["Happy birthday hope you have the best day","Celebrating one year at my dream job","Homemade chocolate cake for the win"],"related":["🥳","🎉","🎁","🧁","🎈"],"cat":"food"},
  {"e":"💪","slug":"flexed-biceps","name":"Flexed Biceps","aliases":"flexed biceps, strong, muscle, power, strength, gym, workout","meaning":"The <strong>Flexed Biceps</strong> (💪) emoji shows a muscular arm flexing. It represents <strong>strength, power, hard work, and determination</strong>. It is the emoji for saying \"you got this\" or celebrating physical and mental fortitude.<br><br>Use it for workout motivation (\"Leg day\"), encouraging someone (\"You are going to crush that interview\"), or acknowledging hard work (\"Putting in the hours\"). It can also mean literal physical strength or biceps. Beyond fitness, 💪 is used for any show of resilience or power: \"Single mom raising three kids working two jobs.\" In group chats, it is a common reaction to someone overcoming a challenge. It is one of the most versatile positive-affirmation emojis.","usage":["Gym session complete you got this","Nailed the presentation today","Working through challenges one day at a time"],"related":["👍","🔥","💯","🏋️","👏"],"cat":"gestures"},
  {"e":"🧊","slug":"ice","name":"Ice Cube","aliases":"ice, cold, cool, chill, frozen, ice cube","meaning":"The <strong>Ice Cube</strong> (🧊) emoji shows a translucent blue ice cube. At face value, it is <strong>literal ice</strong> — for drinks, injuries, or cold things. But it has also been adopted as a symbol for <strong>being cool, unbothered, or emotionally cold</strong>.<br><br>Literally: \"Iced coffee weather\" or \"Put some ice on that sprain.\" Figuratively: \"He is so cold to everyone\" or \"Staying ice cold under pressure.\" In jewelry and fashion contexts, 🧊 can mean diamonds or ice (slang for expensive jewelry): \"New chain.\" The versatility comes from its simplicity — a single, recognizable object that can mean temperature, attitude, or wealth depending on context.","usage":["Iced coffee season is here","She gave him the cold shoulder","Staying cool under all this pressure"],"related":["🥶","❄️","💎","🥵","✨"],"cat":"food"},
  {"e":"🎭","slug":"performing-arts","name":"Performing Arts","aliases":"theatre, drama, acting, performance, masks, comedy and tragedy","meaning":"The <strong>Performing Arts</strong> (🎭) emoji shows the classic comedy and tragedy masks — one smiling, one frowning. It represents <strong>theatre, drama, acting, and storytelling</strong>. But in everyday digital communication, it has a more pointed meaning: <strong>being dramatic or two-faced</strong>.<br><br>Literally: \"Opening night at the theatre.\" Figuratively: \"She is being so dramatic about this situation.\" Or even more pointedly: \"He acts nice but says terrible things behind people's backs.\" The duality of the two masks speaks to the idea of performing different emotions for different audiences — authenticity vs. acting. Use it for theatre kids, drama enthusiasts, or calling out performative behavior.","usage":["Opening night was incredible","Stop being so dramatic about everything","Pretending to be nice when you are not"],"related":["🤡","🎪","🎬","😏","🙄"],"cat":"activities"},
  {"e":"🫂","slug":"people-hugging","name":"People Hugging","aliases":"hug, embrace, comfort, support, hugging, holding each other","meaning":"The <strong>People Hugging</strong> (🫂) emoji shows two figures embracing. Introduced in 2022, it filled a long-standing gap in the emoji keyboard — a way to say <strong>\"I am giving you a hug\" or \"I am here for you.\"</strong> It represents comfort, support, and physical affection in a way that ❤️ (heart) cannot quite match.<br><br>Use it when someone is going through a hard time (\"Sending you the biggest hug\"), when you are reunited with someone (\"Finally seeing my best friend after two years\"), or when you just need to express warmth (\"This community is so supportive\"). Unlike 🤗 (hugging face), which shows one person offering a hug, 🫂 shows mutual embrace — both people are in it together. The blue silhouettes make it gender-neutral and universally relatable.","usage":["Sending love to everyone going through it right now","Reunited with my family after so long","You are not alone in this"],"related":["🤗","❤️","🥺","💕","🙏"],"cat":"gestures"},
  {"e":"🧘","slug":"person-in-lotus-position","name":"Person in Lotus Position","aliases":"yoga, meditation, zen, calm, mindfulness, inner peace","meaning":"The <strong>Person in Lotus Position</strong> (🧘) emoji shows a person sitting cross-legged in meditation pose. It represents <strong>yoga, meditation, mindfulness, and inner peace</strong>. It is the emoji for when you are trying to stay calm in a chaotic world.<br><br>Use it literally about yoga or meditation (\"Morning yoga session\"), or figuratively about staying centered (\"Me trying to stay calm while everyone is panicking\"). It can also mean \"I am removing myself from this drama\": \"Not getting involved in that conversation.\" In wellness communities, it is a standard marker for self-care and mental health. The lotus position is recognized globally as a symbol of meditation and spiritual practice.","usage":["Starting the day with 20 minutes of meditation","Staying zen while the world burns around me","Not engaging with the drama today"],"related":["😌","🕉️","🧎","😮‍💨","✨"],"cat":"gestures"},
]

with open('/Users/fanny/DevProjects/Tools/emoji101/generate_meanings.py', 'r') as f:
    content = f.read()

more_start = content.find('MORE_DATA = [')
bracket = content.find('\n]', more_start)
if bracket == -1:
    bracket = content.find(']', more_start)

new_code = ',\n'.join([json.dumps(e, ensure_ascii=False) for e in entries])
content = content[:bracket] + ',\n' + new_code + '\n' + content[bracket:]

with open('/Users/fanny/DevProjects/Tools/emoji101/generate_meanings.py', 'w') as f:
    f.write(content)

print(f'Added {len(entries)} more entries. Now regenerating...')
